export const mockSummary = {
  total_scrapers: 13,
  healthy: 8,
  degraded: 2,
  down: 1,
  disabled: 2,
  total_jobs_24h: 1500,
};

export const mockScrapers = [
  {
    scraper_name: "indeed",
    display_name: "Indeed",
    is_enabled: true,
    requires_auth: false,
    scraper_type: "html" as const,
    health_status: "healthy" as const,
    selector_health: "healthy" as const,
    success_rate_24h: 95,
    avg_duration_ms: 2500,
    last_success: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    last_error: null,
    total_runs_24h: 24,
    jobs_found_24h: 150,
    rate_limit_per_hour: 60,
  },
  {
    scraper_name: "usajobs",
    display_name: "USAJobs",
    is_enabled: true,
    requires_auth: true,
    scraper_type: "api" as const,
    health_status: "degraded" as const,
    selector_health: "unknown" as const,
    success_rate_24h: 72,
    avg_duration_ms: 3500,
    last_success: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    last_error: "Rate limited",
    total_runs_24h: 20,
    jobs_found_24h: 80,
    rate_limit_per_hour: 30,
  },
  {
    scraper_name: "lever",
    display_name: "Lever",
    is_enabled: false,
    requires_auth: false,
    scraper_type: "api" as const,
    health_status: "disabled" as const,
    selector_health: "degraded" as const,
    success_rate_24h: 0,
    avg_duration_ms: null,
    last_success: null,
    last_error: null,
    total_runs_24h: 0,
    jobs_found_24h: 0,
    rate_limit_per_hour: 20,
  },
  {
    scraper_name: "monster",
    display_name: "Monster",
    is_enabled: true,
    requires_auth: false,
    scraper_type: "html" as const,
    health_status: "down" as const,
    selector_health: "broken" as const,
    success_rate_24h: 35,
    avg_duration_ms: 5000,
    last_success: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    last_error: "Connection timeout",
    total_runs_24h: 10,
    jobs_found_24h: 5,
    rate_limit_per_hour: 40,
  },
  {
    scraper_name: "remoteok",
    display_name: "Remote OK",
    is_enabled: true,
    requires_auth: false,
    scraper_type: "rss" as const,
    health_status: "healthy" as const,
    selector_health: "unknown" as const,
    success_rate_24h: 98,
    avg_duration_ms: 1200,
    last_success: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    last_error: null,
    total_runs_24h: 12,
    jobs_found_24h: 40,
    rate_limit_per_hour: 60,
  },
];

export const mockRuns = [
  {
    id: 1,
    scraper_name: "indeed",
    started_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 29 * 60 * 1000).toISOString(),
    duration_ms: 2500,
    status: "success" as const,
    jobs_found: 15,
    jobs_new: 3,
    error_message: null,
    error_code: null,
    retry_attempt: 0,
  },
  {
    id: 2,
    scraper_name: "indeed",
    started_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    finished_at: new Date(Date.now() - 89 * 60 * 1000).toISOString(),
    duration_ms: 3000,
    status: "error" as const,
    jobs_found: 0,
    jobs_new: 0,
    error_message: "Timeout",
    error_code: "TIMEOUT",
    retry_attempt: 1,
  },
];

export const mockTestResults = [
  {
    scraper_name: "indeed",
    test_type: "connectivity" as const,
    passed: true,
    duration_ms: 1200,
    details: null,
    error: null,
  },
  {
    scraper_name: "usajobs",
    test_type: "connectivity" as const,
    passed: false,
    duration_ms: 5000,
    details: null,
    error: "Connection refused",
  },
];
