import * as model from "./jobSourceDiscoveryModel";
import { JOB_SOURCE_SPECIALIZED_BOARD_ENTRIES } from "./jobSourceDiscoverySpecializedBoardsEntries";

export const JOB_SOURCE_BOARDS_DISCOVERY_ENTRIES: readonly model.JobSourceDiscoveryEntry[] = [
  {
    id: "indeed",
    label: "Indeed",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["indeed.com"],
    examples: ["Indeed job search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "monster",
    label: "Monster",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US", "global"],
    careerProfileIds: "all",
    hostPatterns: ["monster.com"],
    examples: ["Monster job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "ziprecruiter",
    label: "ZipRecruiter",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["ziprecruiter.com"],
    examples: ["ZipRecruiter search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "careerbuilder",
    label: "CareerBuilder",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["careerbuilder.com"],
    examples: ["CareerBuilder search results"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "glassdoor",
    label: "Glassdoor",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "manual-only",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["glassdoor.com"],
    examples: ["Glassdoor job search"],
    implementationPath:
      "Use a user-opened search, visible Browser Import, or manual entry. Scheduled and pasted-URL fetches are policy-disabled.",
    notes: model.POLICY_BLOCKED_AUTOMATION_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "simplyhired",
    label: "SimplyHired",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "manual-only",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: ["simplyhired.com"],
    examples: ["SimplyHired search results"],
    implementationPath:
      "Use a user-opened search, visible Browser Import, or manual entry. Scheduled and pasted-URL fetches are policy-disabled.",
    notes: model.POLICY_BLOCKED_AUTOMATION_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "cv-library",
    label: "CV-Library",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["cv-library.co.uk"],
    examples: ["CV-Library UK job search"],
    implementationPath:
      "Use user-opened import unless official partner API access is configured and reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "totaljobs",
    label: "Totaljobs",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "restricted",
    regions: ["UK"],
    careerProfileIds: "all",
    hostPatterns: ["totaljobs.com"],
    examples: ["Totaljobs UK job search"],
    implementationPath:
      "Use user-opened import or explicit user-gated access only.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "stepstone",
    label: "StepStone",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Europe", "UK"],
    careerProfileIds: "all",
    hostPatterns: ["stepstone.de", "stepstone.fr", "stepstone.co.uk"],
    examples: ["StepStone Germany", "StepStone France", "StepStone UK"],
    implementationPath:
      "Use user-opened import until country-specific access terms and platform behavior are reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "xing-jobs",
    label: "XING Jobs",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["Germany", "Austria", "Switzerland"],
    careerProfileIds: "all",
    hostPatterns: ["xing.com"],
    examples: ["XING jobs in German-speaking markets"],
    implementationPath:
      "Use user-opened import only until professional-network account behavior and source terms are reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "otta",
    label: "Otta",
    category: "startup-job-board",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US", "UK", "Europe", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["otta.com"],
    examples: ["Curated startup and technology roles"],
    implementationPath:
      "Use user-opened import only; treat Otta account and personalization surfaces as restricted.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "welcome-to-the-jungle",
    label: "Welcome to the Jungle",
    category: "startup-job-board",
    accessModel: "review-required",
    status: "research",
    regions: ["Europe", "UK", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
      "customer-success",
    ],
    hostPatterns: ["welcometothejungle.com"],
    examples: ["European startup and employer profile jobs"],
    implementationPath:
      "Review structured page/API behavior before any native adapter; otherwise use user-opened import.",
    notes:
      "Useful European startup and employer discovery surface, but source-specific access and attribution need review.",
  },
  {
    id: "builtin",
    label: "Built In",
    category: "regional-local",
    accessModel: "restricted-user-gated",
    status: "manual-only",
    regions: ["US"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["builtin.com", "builtincolorado.com"],
    locationSearchPatterns: [
      "/jobs",
      "/jobs?state=<state>&country=<country>&allLocations=true",
      "/jobs?city=<city>&state=<state>&country=<country>&allLocations=true",
      "regional city hosts such as builtincolorado.com/jobs",
    ],
    examples: [
      "Built In network jobs",
      "Built In California",
      "Built In San Francisco",
      "Built In Colorado",
      "Built In NYC",
      "Built In Chicago",
    ],
    implementationPath:
      "Use a user-opened search, visible Browser Import, or manual entry. Scheduled and pasted-URL fetches are policy-disabled.",
    notes: model.POLICY_BLOCKED_AUTOMATION_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "regional-industry-boards",
    label: "Regional Industry Boards",
    category: "regional-local",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["US", "global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["builtin*.com", "local industry council job boards"],
    examples: [
      "Built In Colorado",
      "local industry council job boards",
      "regional startup community job boards",
    ],
    implementationPath:
      "Treat regional boards as source-discovery candidates. Prefer employer-career follow-through and require explicit user agreement before board automation.",
    notes:
      "Regional sites are high-value for location-bound users, but access models vary by city and operator.",
    requiresUserAgreement: true,
  },
  {
    id: "state-workforce-boards",
    label: "State Workforce Boards",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["US"],
    careerProfileIds: "all",
    hostPatterns: [
      "state workforce job banks",
      "state labor department job boards",
    ],
    examples: [
      "state workforce center jobs",
      "state department of labor job banks",
      "American Job Center-linked listings",
    ],
    implementationPath:
      "Research each jurisdiction. Prefer official feeds where available, otherwise offer user-opened search links and manual import.",
    notes:
      "Important for local, frontline, government-adjacent, and broad-market roles that may not appear on national boards.",
  },
  {
    id: "city-county-careers",
    label: "City and County Careers",
    category: "public-sector",
    accessModel: "employer-career-system",
    status: "research",
    regions: ["global"],
    careerProfileIds: model.GOVERNMENT_FRIENDLY_PROFILE_IDS,
    hostPatterns: [
      "city career pages",
      "county career pages",
      "municipal applicant portals",
    ],
    examples: [
      "city government careers",
      "county government jobs",
      "public utility career pages",
    ],
    implementationPath:
      "Detect ATS platform first. If no stable public endpoint exists, use user-opened search, pasted job links, or manual entry.",
    notes:
      "Many local public employers use vendor portals or custom pages; model them as employer-career discovery instead of broad scraping.",
  },
  {
    id: "local-chambers-economic-development",
    label: "Local Chambers and Economic Development Boards",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: [
      "chamber job boards",
      "economic development job boards",
      "regional business association job boards",
    ],
    examples: [
      "local chamber of commerce job boards",
      "regional economic development job boards",
      "industry association local listings",
    ],
    implementationPath:
      "Use as a discovery path for local employers. Add native source support only after source-specific terms and structure review.",
    notes:
      "Useful for retail, hospitality, operations, trades, office, and small-business roles.",
  },
  {
    id: "local-newspaper-jobs",
    label: "Local Newspaper Jobs",
    category: "regional-local",
    accessModel: "review-required",
    status: "research",
    regions: ["global"],
    careerProfileIds: "all",
    hostPatterns: ["local newspaper job boards", "regional classifieds jobs"],
    examples: ["regional newspaper job boards", "local classified job pages"],
    implementationPath:
      "Use user-opened search and manual import until source-specific rights and structure are reviewed.",
    notes:
      "Can surface local roles missed by national boards, but source behavior varies widely.",
  },
  {
    id: "dice",
    label: "Dice",
    category: "broad-job-board",
    accessModel: "restricted-user-gated",
    status: "manual-only",
    regions: ["US"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["dice.com"],
    examples: ["Technology job search"],
    implementationPath:
      "Use a user-opened search, visible Browser Import, or manual entry. Scheduled and pasted-URL fetches are policy-disabled.",
    notes: model.POLICY_BLOCKED_AUTOMATION_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "wellfound",
    label: "Wellfound",
    category: "startup-job-board",
    accessModel: "restricted-user-gated",
    status: "research",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: ["wellfound.com"],
    examples: ["Startup hiring"],
    implementationPath:
      "Research current access model. Prefer user-opened import until reviewed.",
    notes: model.RESTRICTED_BOARD_NOTES,
    requiresUserAgreement: true,
  },
  {
    id: "yc-work-at-a-startup",
    label: "Y Combinator Work at a Startup",
    category: "startup-job-board",
    accessModel: "review-required",
    status: "manual-only",
    regions: ["global"],
    careerProfileIds: [
      ...model.TECH_PROFILE_IDS,
      ...model.BUSINESS_PROFILE_IDS,
      ...model.CREATIVE_PROFILE_IDS,
    ],
    hostPatterns: [
      "ycombinator.com/jobs",
      "ycombinator.com/companies/jobs",
    ],
    examples: ["YC startup jobs"],
    implementationPath: "Open the YC search in the user's browser.",
    notes:
      "Automated extraction is unavailable because current YC terms prohibit scraping and similar data gathering.",
  },
  {
    id: "hacker-news-who-is-hiring",
    label: "Hacker News Who Is Hiring",
    category: "public-community",
    accessModel: "public-community",
    status: "supported",
    regions: ["global"],
    careerProfileIds: model.TECH_PROFILE_IDS,
    hostPatterns: ["news.ycombinator.com/item"],
    examples: ["Monthly Who Is Hiring thread"],
    implementationPath: "Native Hacker News source.",
    notes:
      "Community postings need quality and risk scoring because detail levels vary.",
  },
  ...JOB_SOURCE_SPECIALIZED_BOARD_ENTRIES,
] as const;
